- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - role: clickhouse-role

- name: Vector | Install rpm
  hosts: vector
  
- name: Install lighthouse
  hosts: lighthouse
  handlers:  
    - name: start-nginx
      become: true
      command: nginx  
    - name: reload-nginx
      become: true
      command: nginx -s reload
  tasks:
    - name: NGINX | Install epel-release
      become: true
      ansible.builtin.yum:
        name: epel-release
        state: present
    - name: NGINX | Install NGINX
      become: true
      ansible.builtin.yum:
        name: nginx
        state: present
    - name: NGINX | Create Config
      become: true
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: 0644
      notify: start-nginx
  roles:
    - role: lighthouse-role