- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - role: clickhouse-role

- name: Vector | Install rpm
  hosts: vector
  roles:
    - role: vector-role
  
- name: Install lighthouse
  hosts: lighthouse
  roles:
    - role: lighthouse-role