vector_version: "0.21.1-1"
vector_config:
  sources:
    dummy_logs:
      type: demo_logs
      format: syslog
      interval: 1

  transforms:
    parse_logs:
      inputs:
      - dummy_logs
      source: |-
        . = parse_syslog!(string!(.message))
      type: remap

  sinks:
    my_sink_id:
      type: clickhouse
      inputs:
        - parse_logs
      database: logs
      endpoint: 'http://localhost:8123'
      table: logstable
      compression: gzip

  api:
    enabled: true
    address: '127.0.0.1:8686'