---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.100.100
      ansible_user: glisikh

vector:
  hosts:
    vector-01:
      ansible_host: 51.250.65.206
      ansible_user: glisikh
  
lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 158.160.101.23
      ansible_user: glisikh